bboard/bboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views
from .views import *

app_name = 'main'

urlpatterns = [
                  path('', views.index, name='index'),
                  path('accounts/login/', BBLoginView.as_view(), name='login'),
                  path('accounts/register/', RegisterUserView.as_view(), name='register'),
                  path('accounts/logout/', views.logout_view, name='logout'),
                  path('accounts/profile', ProfileListView.as_view(), name='profile'),
                  path('products/', ProductListView.as_view(), name='products'),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# path('products/detail', ProductsView.as_view(), name='products'),

bboard/api/models.py
from django.db import models

# Create your models here.

bboard/main/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustUser(AbstractUser):
    avatar = models.ImageField(upload_to='avatars/', blank=True)


class Profile(models.Model):
    user = models.ForeignKey(CustUser, on_delete=models.CASCADE)


class Product(models.Model):
    SHORT_SIZE = {
        "S": "Small",
        "L": "Litle",
        "M": "Middle",
    }
    title = models.CharField(max_length=60)
    short_size = models.CharField(max_length=1, choices=SHORT_SIZE)
    image = models.ImageField(upload_to='products', blank=True)

bboard/main/forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustUser


class RegisterUserForm(UserCreationForm):
    class Meta:
        model = CustUser
        fields = ["username", "email", "password1", "password2"]

bboard/api/views.py
from django.shortcuts import render

# Create your views here.

bboard/main/views.py
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, ListView

from .forms import RegisterUserForm
from .models import CustUser, Profile, Product


def index(request):
    return render(request, 'main/index.html')


class BBLoginView(LoginView):
    template_name = 'main/login.html'


class RegisterUserView(CreateView):
    model = CustUser
    form_class = RegisterUserForm
    template_name = 'main/register.html'
    success_url = reverse_lazy('main:login')


def logout_view(request):
    logout(request)

@login_required
def logout_view(request):
    logout(request)
    return redirect('main:index')


class ProfileListView(LoginRequiredMixin, generic.ListView):
    model = Profile
    template_name = 'main/profile.html'


class ProductListView(LoginRequiredMixin, generic.ListView):
    model = Product
    template_name = 'main/products.html'
    context_object_name = 'products'

bboard/main/templates/base.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <title> {% block title %}{% endblock %} - Интернет-магазин</title>
</head>
<body>
<header>
    <nav>
        <ul>
            <li><a href="{% url 'main:index' %}">Главная</a></li>
            <li><a href="{% url 'main:products' %}">Товары</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'main:profile' %}">Профиль</a></li>
            <li><a href="{% url 'main:logout' %}">Выйти</a></li>
            {% else %}
            <li><a href="{% url 'main:register' %}">Регистрация</a></li>
            <li><a href="{% url 'main:login' %}">Войти</a></li>
            {% endif %}
        </ul>
    </nav>
</header>
<div class="main">
    <div class="container">
        {% block content %} {% endblock %}
    </div>
</div>
</body>
</html>

bboard/main/templates/main/index.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Главная{% endblock %}
{% block content %}
<h2>Главная</h2>
<p>Это интернет-магазин</p>
{% endblock %}

bboard/main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Вход{% endblock %}

{% block content %}
<h2>Вход</h2>

{% if user.is_authenticated %}
<p>Вы уже вошли</p>
{% else %}
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{% url 'main:index' %}">
    {% buttons submit="Войти" %}{% endbuttons %}
</form>
{% endif %}
{% endblock %}

bboard/main/templates/main/products.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Продукты{% endblock %}
{% block content %}
<h2>Продукты</h2>
{% if products %}
{% for product in products %}
<div>
    <div>
        {% if product.image %}
            <img src="{{product.image.url}}" width="250px">
        {% else %}
           <p>Нет изображения</p>
        {% endif %}
    </div>
    <div>
        <p>Название : {{product.title}} </p>
        <p> Размер товара : {{product.short_size}}</p>
    </div>
</div>
{% endfor %}
{% else %}
<p>There are no product here.</p>
{% endif %}
{% endblock %}

bboard/main/templates/main/profile.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Профиль{% endblock %}
{% block content %}
<h2>Профиль</h2>
<p>Здравствуйте, {{user.username}}, это ваш профиль </p>
<div>
    <div>
        {% if user.avatar %}
            <img src="{{user.avatar.url}}" width="250px">
        {% else %}
            <img src="/media/avatars/default.png" width="250px">
        {% endif %}
    </div>
    <div>
        <p>Имя : {{user.username}} </p>
        <p>Почта : {{user.email}}</p>
    </div>
</div>
{% endblock %}

bboard/main/templates/main/register.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Регистрация{% endblock %}

{% block content %}
<h2>Регистрация</h2>
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form layout='horizontal' %}
    <input type="hidden" name="next" value="{% url 'main:login' %}">
    {% buttons submit="Зарегистрировать" %}{% endbuttons %}
</form>
{% endblock %}